Repository MPAS-Dev/pyremap, pull requests merged in 2025-04, with the labels that each got.

#104 Add `ruff`, `flynt`, and `mypy` to linter and lint all existing code
  .flake8
  .pre-commit-config.yaml
  dev-spec.txt
  pyproject.toml
  pyremap/__init__.py
  pyremap/descriptor/__init__.py
  pyremap/descriptor/lat_lon_2d_grid_descriptor.py
  pyremap/descriptor/lat_lon_grid_descriptor.py
  pyremap/descriptor/mesh_descriptor.py
  pyremap/descriptor/mpas_cell_mesh_descriptor.py
  pyremap/descriptor/mpas_edge_mesh_descriptor.py
  pyremap/descriptor/mpas_vertex_mesh_descriptor.py
  pyremap/descriptor/point_collection_descriptor.py
  pyremap/descriptor/projection_grid_descriptor.py
  pyremap/descriptor/utility.py
  pyremap/polar.py
  pyremap/remapper/build_map.py
  pyremap/remapper/descriptor.py
  pyremap/remapper/ncremap.py
  pyremap/remapper/remap_numpy.py
  pyremap/remapper/remapper.py
  pyremap/remapper/setup.py
  pyremap/test/__init__.py
  pyremap/test/test_interpolate.py
  pyremap/utility.py
Labels: dependencies

#105 Fix the version dropdown based on ChatGPT's suggestions
  docs/_templates/layout.html
  docs/conf.py
  docs/shared/version-switcher.js
Labels: documentation

#106 Fix the destination dimension name from `ncremap`
  examples/make_lat_lon_to_mpas_mapping.py
  pyremap/remapper/ncremap.py
  pyremap/test/__init__.py
  pyremap/test/test_interpolate.py
  pyremap/test/test_interpolate/ref_latlon_file_to_point_collection.nc
  pyremap/test/test_interpolate/ref_latlon_to_mpas_cell.nc
Labels: bug

#109 Fix expand of cells in SCRIP files
  pyremap/descriptor/lat_lon_2d_grid_descriptor.py
  pyremap/descriptor/lat_lon_grid_descriptor.py
  pyremap/descriptor/mpas_cell_mesh_descriptor.py
  pyremap/descriptor/mpas_edge_mesh_descriptor.py
  pyremap/descriptor/mpas_vertex_mesh_descriptor.py
  pyremap/descriptor/projection_grid_descriptor.py
  pyremap/descriptor/utility.py
  tests/test_interpolate.py
  tests/test_interpolate/ref_latlon_to_mpas_cell_expand.nc
Labels: bug

#110 Add a logger to to the build_map() method
  pyremap/remapper/build_map.py
  pyremap/remapper/remapper.py
Labels: bug

#111 Add more optional arguments to the remapper init
  pyremap/remapper/remapper.py
Labels: enhancement

#112 Switch CI from `miniconda` to `micromamba`
  .github/workflows/build_workflow.yml
  .github/workflows/docs_workflow.yml
Labels: ci

#114 Fixes to docs
  docs/conf.py
  docs/developer_guide/generate_preview_docs.md
  docs/generate_versions_json.py
Labels: bug, documentation, ci
